### ISSUE TITLE
Why the training process take up 100% CPU?

### ISSUE THREAD

**Issue by edwardnguyen1705** [tnikolla/grasp-detection#26]
Hi, Why the training process takes up 100% CPU? 
Does the calling the function distorted_inputs() cause that?

**Comment by WuXingrui** [comment]
I meet the same question，it seems that the gpu doesn't work in this job

**Comment by edwardnguyen1705** [comment]
Hi @WuXingrui , just wait, I will upload a Pytorch implementation of the same paper.
